In [4]:
from utils import *

# Seasonal Player Data

In [5]:
URL = 'https://1xbet.whoscored.com/regions/252/tournaments/2/seasons/10316/stages/23400/playerstatistics/england-premier-league-2024-2025'
PL2425_player = crwaling_player_stats_at_once(URL)

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/0n/d2rdhpkj2lq5h2j83266pz3r0000gn/T/ipykernel_17447/221449293.py", line 2, in <module>
    PL2425_player = crwaling_player_stats_at_once(URL)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/Documents/GitHub/whoscored_crawling/utils.py", line 1020, in crwaling_player_stats_at_once
    print('player stats offensive : done')
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/Documents/GitHub/whoscored_crawling/utils.py", line 695, in crawling_player_statistics
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    self.service.start()
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 106, in start
    sleep(min(0.01 + 0.05 * count, 0.5))
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1428, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1319, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1172, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1087, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 969, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
    ^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
           ^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
           ^^^^^
  File "/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/executing/executing.py", line 190, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

In [ ]:
PL2425_player.head(10)

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Mohamed Salah,26,Liverpool,33,"AM(CLR),FW",38,3380,18,2.3,30.4,...,1.8,3.1,0.6,0.2,0.7,0,0.1,0.2,0,0
1,Bukayo Saka,13,Arsenal,24,"D(L),M(CLR)",20(5),1737,10,2.3,23.9,...,1.6,1.4,1.2,0.1,0.6,0,0.2,0.4,0,0
2,Cole Palmer,15,Chelsea,23,"AM(CR),FW",36(1),3199,8,2.4,35.4,...,1,1.9,0.9,0.3,0.4,0.1,0.5,0.4,0,0
3,Bryan Mbeumo,189,Brentford,26,"AM(CLR),FW",38,3417,7,1.8,28.7,...,1.2,2.8,1.3,0.4,0.7,0,1.3,0.4,0.1,0
4,Erling Haaland,167,Man City,25,FW,31,2742,3,0.9,12.1,...,0.9,1.5,0.4,0.2,0.8,0,0.7,0.2,0,0
5,Matheus Cunha,161,Wolves,26,"AM(CL),FW",29(4),2604,6,1.7,28.8,...,1.7,2.4,1.2,0.5,1.3,0,0.6,0.8,0,0
6,Alexander Isak,23,Newcastle,26,"AM(L),FW",34,2774,6,1.2,19.4,...,1.6,1.9,0.4,0.1,0.8,0,0.5,0.3,0.1,0
7,Luis Díaz,26,Liverpool,29,"AM(LR),FW",28(8),2413,5,1.6,22.9,...,1.4,1.5,1.1,0.2,1.3,0,0.2,0.7,0,0
8,Bruno Fernandes,32,Man Utd,31,"M(CLR),FW",35(1),3024,10,2.5,56.1,...,1.2,1.2,2.3,0.7,0.9,0,0.8,1.4,0.2,0
9,Antoine Semenyo,183,Bournemouth,26,"AM(LR),FW",36(1),3210,5,1.2,26.9,...,2.1,2.3,1.5,0.3,2,0.1,0.9,0.7,0.2,0

# Seasonal Team Data

In [ ]:
URL = 'https://1xbet.whoscored.com/regions/252/tournaments/2/seasons/10316/england-premier-league'
PL2425_team = league_table_added(URL)

In [ ]:
PL2425_team.to_csv('./team_data/PL2425_team.csv', index=False)
PL2425_team.head(10)

,team_name,P,W,D,L,GF,GA,GD,Pts,Goals,...,A_Won,Rating,Shoted pg,Tackles pg,Intercept pg,Fouls pg,Offsides pg,Shots OT pg,Dribbles pg,Fouled pg
0,Liverpool,38,25,9,4,86,41,+45,84,86,...,10.8,6.81,10.2,16.9,7.9,11.3,1.6,6.1,7.9,9.4
1,Arsenal,38,20,14,4,69,34,+35,74,69,...,12.7,6.77,9.5,15.7,5.9,10.6,2.1,4.9,8.4,10.7
2,Manchester City,38,21,8,9,72,44,+28,71,72,...,8.2,6.76,9.3,13.1,6,7.6,1.2,5.7,9.9,10.1
3,Chelsea,38,20,9,9,64,43,+21,69,64,...,10.8,6.70,10.5,15.5,7.2,11.5,1.7,5.7,8.6,11.7
4,Newcastle,38,20,6,12,68,47,+21,66,68,...,13.2,6.71,12.4,15.9,7.1,10.4,1.9,4.6,7.4,11.8
5,Aston Villa,38,19,9,10,58,51,+7,66,58,...,10.2,6.62,12.2,16.8,6.3,10.7,1.4,4.5,8.6,13.1
6,Nottingham Forest,38,19,8,11,58,46,+12,65,58,...,15.2,6.70,14,18.4,8.5,10.6,2.4,4.4,6.8,11
7,Brighton,38,16,13,9,66,59,+7,61,66,...,13.9,6.62,11.2,18.6,8.3,11.5,1.2,5,8.9,10.8
8,Bournemouth,38,15,11,12,58,46,+12,56,58,...,15.3,6.71,12.8,18.2,9.2,13.8,1.8,5.3,7.7,10.5
9,Brentford,38,16,8,14,66,57,+9,56,66,...,16.6,6.72,17,16.7,7.5,8.4,1.7,4.8,7,8.9

# Seasonal Match Data

In [ ]:
crawling_all_matches(252,2,10316,'PL2425')

find PL2425_match_url.csvdone
match_url 1 : crawling done
match_url 2 : crawling done
match_url 3 : crawling done
match_url 4 : crawling done
match_url 5 : crawling done
match_url 6 : crawling done
match_url 7 : crawling done
match_url 8 : crawling done
match_url 9 : crawling done
match_url 10 : crawling done
match_url 11 : crawling done
match_url 12 : crawling done
match_url 13 : crawling done
match_url 14 : crawling done
match_url 15 : crawling done
match_url 16 : crawling done
match_url 17 : crawling done
match_url 18 : crawling done
match_url 19 : crawling done
match_url 20 : crawling done
match_url 21 : crawling done
match_url 22 : crawling done
match_url 23 : crawling done
match_url 24 : crawling done
match_url 25 : crawling done
match_url 26 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 27 : crawling done
match_url 28 : crawling done
match_url 29 : crawling done
match_url 30 : crawling done
match_url 31 : crawling done
match_url 32 : crawling done
match_url 33 : crawling done
match_url 34 : crawling done
match_url 35 : crawling done
match_url 36 : crawling done
match_url 37 : crawling done
match_url 38 : crawling done
match_url 39 : crawling done
match_url 40 : crawling done
match_url 41 : crawling done
match_url 42 : crawling done
match_url 43 : crawling done
match_url 44 : crawling done
match_url 45 : crawling done
match_url 46 : crawling done
match_url 47 : crawling done
match_url 48 : crawling done
match_url 49 : crawling done
match_url 50 : crawling done
match_url 51 : crawling done
match_url 52 : crawling done
match_url 53 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 54 : crawling done
match_url 55 : crawling done
match_url 56 : crawling done
match_url 57 : crawling done
match_url 58 : crawling done
match_url 59 : crawling done
match_url 60 : crawling done
match_url 61 : crawling done
match_url 62 : crawling done
match_url 63 : crawling done
match_url 64 : crawling done
match_url 65 : crawling done
match_url 66 : crawling done
match_url 67 : crawling done
match_url 68 : crawling done
match_url 69 : crawling done
match_url 70 : crawling done
match_url 71 : crawling done
match_url 72 : crawling done
match_url 73 : crawling done
match_url 74 : crawling done
match_url 75 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 76 : crawling done
match_url 77 : crawling done
match_url 78 : crawling done
match_url 79 : crawling done
match_url 80 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 81 : crawling done
match_url 82 : crawling done
match_url 83 : crawling done
match_url 84 : crawling done
match_url 85 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 86 : crawling done
match_url 87 : crawling done
match_url 88 : crawling done
match_url 89 : crawling done
match_url 90 : crawling done
match_url 91 : crawling done
match_url 92 : crawling done
match_url 93 : crawling done
match_url 94 : crawling done
match_url 95 : crawling done
match_url 96 : crawling done
match_url 97 : crawling done
match_url 98 : crawling done
match_url 99 : crawling done
match_url 100 : crawling done
match_url 101 : crawling done
match_url 102 : crawling done
match_url 103 : crawling done
match_url 104 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 105 : crawling done
match_url 106 : crawling done
match_url 107 : crawling done
match_url 108 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 109 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 110 : crawling done
match_url 111 : crawling done
match_url 112 : crawling done
match_url 113 : crawling done
match_url 114 : crawling done
match_url 115 : crawling done
match_url 116 : crawling done
match_url 117 : crawling done
match_url 118 : crawling done
match_url 119 : crawling done
match_url 120 : crawling done
match_url 121 : crawling done
match_url 122 : crawling done
match_url 123 : crawling done
match_url 124 : crawling done
match_url 125 : crawling done
match_url 126 : crawling done
match_url 127 : crawling done
match_url 128 : crawling done
match_url 129 : crawling done
match_url 130 : crawling done
match_url 131 : crawling done
match_url 132 : crawling done
match_url 133 : crawling done
match_url 134 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 135 : crawling done
match_url 136 : crawling done
match_url 137 : crawling done
match_url 138 : crawling done
match_url 139 : crawling done
match_url 140 : crawling done
match_url 141 : crawling done
match_url 142 : crawling done
match_url 143 : crawling done
match_url 144 : crawling done
match_url 145 : crawling done
match_url 146 : crawling done
match_url 147 : crawling done
match_url 148 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 149 : crawling done
match_url 150 : crawling done
match_url 151 : crawling done
match_url 152 : crawling done
match_url 153 : crawling done
match_url 154 : crawling done
match_url 155 : crawling done
match_url 156 : crawling done
match_url 157 : crawling done
match_url 158 : crawling done
match_url 159 : crawling done
match_url 160 : crawling done
match_url 161 : crawling done
match_url 162 : crawling done
match_url 163 : crawling done
match_url 164 : crawling done
match_url 165 : crawling done
match_url 166 : crawling done
match_url 167 : crawling done
match_url 168 : crawling done
match_url 169 : crawling done
match_url 170 : crawling done
match_url 171 : crawling done
match_url 172 : crawling done
match_url 173 : crawling done
match_url 174 : crawling done
match_url 175 : crawling done
match_url 176 : crawling done
match_url 177 : crawling done
match_url 178 : crawling done
match_url 179 : crawling done
match_url 180 : crawling done
match_url 181 : crawling done
match_url 182 : crawling done
match_url 183 : crawling done
match_url 184 : crawling done
match_url 185 : crawling done
match_url 186 : crawling done
match_url 187 : crawling done
match_url 188 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 189 : crawling done
match_url 190 : crawling done
match_url 191 : crawling done
match_url 192 : crawling done
match_url 193 : crawling done
match_url 194 : crawling done
match_url 195 : crawling done
match_url 196 : crawling done
match_url 197 : crawling done
match_url 198 : crawling done
match_url 199 : crawling done
match_url 200 : crawling done
match_url 201 : crawling done
match_url 202 : crawling done
match_url 203 : crawling done
match_url 204 : crawling done
match_url 205 : crawling done
match_url 206 : crawling done
match_url 207 : crawling done
match_url 208 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 209 : crawling done
match_url 210 : crawling done
match_url 211 : crawling done
match_url 212 : crawling done
match_url 213 : crawling done
match_url 214 : crawling done
match_url 215 : crawling done
match_url 216 : crawling done
match_url 217 : crawling done
match_url 218 : crawling done
match_url 219 : crawling done
match_url 220 : crawling done
match_url 221 : crawling done
match_url 222 : crawling done
match_url 223 : crawling done
match_url 224 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 225 : crawling done
match_url 226 : crawling done
match_url 227 : crawling done
match_url 228 : crawling done
match_url 228 : error
match_url 230 : crawling done
match_url 230 : error
match_url 231 : error
match_url 232 : error
match_url 233 : error
match_url 234 : error
match_url 235 : error
match_url 237 : crawling done
match_url 238 : crawling done
match_url 239 : crawling done
match_url 240 : crawling done
match_url 241 : crawling done
match_url 242 : crawling done
match_url 243 : crawling done
match_url 244 : crawling done
match_url 245 : crawling done
match_url 246 : crawling done
match_url 247 : crawling done
match_url 248 : crawling done
match_url 249 : crawling done
match_url 250 : crawling done
match_url 251 : crawling done
match_url 252 : crawling done
match_url 253 : crawling done
match_url 254 : crawling done
match_url 255 : crawling done
match_url 256 : crawling done
match_url 257 : crawling done
match_url 258 : crawling done
match_url 259 : crawling done
match_url 260 : crawling done
match_url 261 : crawling done
match_url 262 : crawling done
match_url 263 : crawling done
match_url 264 : crawling done
match_url 265 : crawling done
match_url 266 : crawling done
match_url 267 : crawling done
match_url 268 : crawling done
match_url 269 : crawling done
match_url 270 : crawling done
match_url 271 : crawling done
match_url 272 : crawling done
match_url 273 : crawling done
match_url 274 : crawling done
match_url 275 : crawling done
match_url 276 : crawling done
match_url 277 : crawling done
match_url 278 : crawling done
match_url 279 : crawling done
match_url 280 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 281 : crawling done
match_url 282 : crawling done
match_url 283 : crawling done
match_url 284 : crawling done
match_url 285 : crawling done
match_url 286 : crawling done
match_url 287 : crawling done
match_url 288 : crawling done
match_url 289 : crawling done
match_url 290 : crawling done
match_url 291 : crawling done
match_url 292 : crawling done
match_url 293 : crawling done
match_url 294 : crawling done
match_url 295 : crawling done
match_url 296 : crawling done
match_url 297 : crawling done
match_url 298 : crawling done
match_url 299 : crawling done
match_url 300 : crawling done
match_url 301 : crawling done
match_url 302 : crawling done
match_url 303 : crawling done
match_url 304 : crawling done
match_url 305 : crawling done
match_url 306 : crawling done
match_url 307 : crawling done
match_url 308 : crawling done
match_url 309 : crawling done
match_url 310 : crawling done
match_url 311 : crawling done
match_url 312 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 313 : crawling done
match_url 314 : crawling done
match_url 315 : crawling done
match_url 316 : crawling done
match_url 317 : crawling done
match_url 318 : crawling done
match_url 319 : crawling done
match_url 320 : crawling done
match_url 321 : crawling done
match_url 322 : crawling done
match_url 323 : crawling done
match_url 324 : crawling done
match_url 325 : crawling done
match_url 326 : crawling done
match_url 327 : crawling done
match_url 328 : crawling done
match_url 329 : crawling done
match_url 330 : crawling done
match_url 331 : crawling done
match_url 332 : crawling done
match_url 333 : crawling done
match_url 334 : crawling done
match_url 335 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 336 : crawling done
match_url 337 : crawling done
match_url 338 : crawling done
match_url 339 : crawling done
match_url 340 : crawling done
match_url 341 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 342 : crawling done
match_url 343 : crawling done
match_url 344 : crawling done
match_url 345 : crawling done
match_url 346 : crawling done
match_url 347 : crawling done
match_url 348 : crawling done
match_url 349 : crawling done
match_url 350 : crawling done
match_url 351 : crawling done
match_url 352 : crawling done
match_url 353 : crawling done
match_url 354 : crawling done
match_url 355 : crawling done
match_url 356 : crawling done
match_url 357 : crawling done
match_url 358 : crawling done
match_url 359 : crawling done
match_url 360 : crawling done
match_url 361 : crawling done
match_url 362 : crawling done
match_url 363 : crawling done
match_url 364 : crawling done
match_url 365 : crawling done
match_url 366 : crawling done
match_url 367 : crawling done
match_url 368 : crawling done
match_url 369 : crawling done
match_url 370 : crawling done
match_url 371 : crawling done
match_url 372 : crawling done
match_url 373 : crawling done
match_url 374 : crawling done
match_url 375 : crawling done
match_url 376 : crawling done
match_url 377 : crawling done
match_url 378 : crawling done
match_url 379 : crawling done

/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/jaeminiman/anaconda3/envs/pytorch/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

match_url 380 : crawling done
[228, 230, 231, 232, 233, 234, 235]
find PL2425_match_url.csvdone
match_number 228 : cawling done
match_number 230 : cawling done
match_number 231 : cawling done
match_number 232 : cawling done
match_number 233 : cawling done
match_number 234 : cawling done
match_number 235 : cawling done
[]

[]